inventory_name: victoria
inventory_year: 2016
timeslices:
  - 2030
  - 2050
sector_map:
  - source: Dkdsjf
    target: Transportation

scaler:
  name: relative_change
  source_type: CEDS
  scenario: ''

overrides:
  - variable: Emissions|H2
    sector: Industrial
    scaler:
      name: constant
