inventory_name: victoria
inventory_year: 2016

timeslices:
  - 2020
  - 2040
  - 2060

variables:
  - variable: NOx
    sector: industrial
    method:
      name: relative_change
      source_id: CR-MESSAGE-GLOBIOM-ssp245-high
      variable_id: NOx-em-anthro
      sector: Industrial Sector
  - variable: NOx
    sector: motor_vehicles
    method:
      name: relative_change
      source_id: CR-MESSAGE-GLOBIOM-ssp245-high
      variable_id: NOx-em-anthro
      sector: Transportation Sector