# Inspired by https://github.com/LaurenceRawlings/python-poetry-cicd/blob/main/.github/workflows/bump.yml
name: Bump version

on:
  workflow_dispatch:

jobs:
  bump_version:
    name: "Bump version and create changelog"
    if: "!startsWith(github.event.head_commit.message, 'bump:')"
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: "${{ secrets.PERSONAL_ACCESS_TOKEN }}"
      - name: Create bump and changelog
        id: cz
        uses: commitizen-tools/commitizen-action@0.18.1
        with:
          github_token: "${{ secrets.PERSONAL_ACCESS_TOKEN }}"
          branch: main
          check_consistency: true
      - name: Print Version
        run: echo "Bumped to version ${{ steps.cz.outputs.version }}"
